name: PromisedLand
main: me.zhehe.PromisedLand
version: 0.1.0
author: zhehe
load: STARTUP
loadbefore: [Multiverse-Core, dimension-door, multiworld]
api-version: 1.13
description: Floating islands world generator
